### ISSUE TITLE
Question about novelty of M-Schema?

### ISSUE THREAD

**Issue by toandd2** [XGenerationLab/XiYan-SQL#3]
I'm working on the Text-to-SQL problem, and the proposed database representation you suggested seems similar to a rejected work from ICLR 2025.

You can find the discussion here:
https://openreview.net/forum?id=JffVqPWQgg&noteId=yy3MiHujOK

In the discussion, they proposed the following schema language for databases:

```sql
database schema:

table department, columns = [ department_id (int | primary key | values: 1), name (text | values: State, Treasury), ranking (int | values: 1)]
table head, columns = [ head_id (int | primary key | values: 1), name (text | values: Tiger Woods), age (real | values: 67.0)]
table management, columns = [ department_id (int | primary key | values: 2), head_id (int | primary key | values: 5), temporary_acting (text | values: Yes)]
foreign keys: management.head_id = head.head_id, management.department_id = department.department_id

Question:
...
```

I wanted to ask if you could clarify how your proposed solution distinguishes itself from this prior work. Is there a novel aspect of your schema design or any additional features in your approach that set it apart from what was already suggested in this ICLR submission? Any insight into the unique contributions of your approach would be greatly appreciated!

  :> Thanks, hope to see the public checkpoints soon.

**Comment by XGenerationLab** [comment]
Thank you for your question. 

1. M-schema is derived from [MAC-SQL](https://arxiv.org/abs/2312.11242) and does not reference the ICLR submission you mentioned. The details are described in our technical report.
2. Currently, many approaches employ semi-structured schema representation, frequently using table-like or dict-like structures. As a result, the schemas tend to exhibit a degree of similarity.

**Comment by toandd2** [comment]
Thank you for your clarification.
