### ISSUE TITLE
xiyan sql论文中的成绩是用哪个大模型跑出来的

### ISSUE THREAD

**Issue by ukhack** [XGenerationLab/XiYan-SQL#4]
gpt-4o?
在较小参数的模型如qianwen2.5-7b中是否还能有此成绩

**Comment by XGenerationLab** [comment]
感谢您的关注～
xiyan-sql是采用了集成多生成器的独特方案，其中贡献最大的生成器是基于qwen2.5-coder-32b微调得到的；
如果是采用参数较小的模型，集成到我们的xiyansql中也能有不错的效果，不过以模型量级上的经验来看，较于现在的成绩可能会有一些下降。
