### ISSUE TITLE
ngql结果问题

### ISSUE THREAD

**Issue by ccp123456789** [XGenerationLab/XiYan-SQL#5]
论文中提到的ngql效果指标，请问这个地方是有在微调中加入gql训练集吗？ 还是说，纯粹的ICL + 多生成器完成的？

**Comment by XGenerationLab** [comment]
ICL的生成器和SFT的生成器都是有贡献的，我们的SFT生成器也是支持多语言的，包括GQL，因此训练数据当中有少量的GQL数据。

**Comment by ccp123456789** [comment]
> ICL的生成器和SFT的生成器都是有贡献的，我们的SFT生成器也是支持多语言的，包括GQL，因此训练数据当中有少量的GQL数据。

那你们这个怎么能保证泛化性？ 你的训练数据里有可能就包含了图谱数据。 另外，你们的代码怎么又延迟2个月发布了，这也太。。。。
